// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9o_JMRssFNFVNLA4rQbc8S4FsrDpdb6I',
    appId: '1:847765205053:web:fd59061ff99d35875cfa54',
    messagingSenderId: '847765205053',
    projectId: 'attendi-fy-2b84a',
    authDomain: 'attendi-fy-2b84a.firebaseapp.com',
    storageBucket: 'attendi-fy-2b84a.appspot.com',
    measurementId: 'G-4KD3PR0JX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxzptLRrzJwxrsuZHbokb5uIrnj-PFvGE',
    appId: '1:847765205053:android:299a72ce10b70dc95cfa54',
    messagingSenderId: '847765205053',
    projectId: 'attendi-fy-2b84a',
    storageBucket: 'attendi-fy-2b84a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcKjA48F6FL2F5Gxm2NrvEWBIr4baRpjs',
    appId: '1:847765205053:ios:27b5644656afe9595cfa54',
    messagingSenderId: '847765205053',
    projectId: 'attendi-fy-2b84a',
    storageBucket: 'attendi-fy-2b84a.appspot.com',
    iosClientId: '847765205053-64cf5lvrs63sdh26aune4psv1bo1td95.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendify',
  );
}
